{
 "title": "Technical",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Disponibilidad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP Voting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Conteo Peticiones Python",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=\"api\", path=\"/videos/upload\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje Exito API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (http_requests_total{job=\"api\", path=\"/videos/upload\", status=\"201\"} / http_requests_total{job=\"api\", path=\"/videos/upload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operaciones por Segundo Python",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{job=\"api\", path=\"/videos/upload\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latencia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Latencias Python",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"api\", path=\"/videos/upload\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU & Memoria",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Voting",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"service-voting\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Java",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"service-java\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memoria Voting",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"service-voting\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"service-voting\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"service-voting\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memoria Java",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"service-java\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"service-voting\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"service-voting\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}