services:
  api:
    build:
      context: ./APIRestful
      dockerfile: Dockerfile
    container_name: anb_api
    ports:
      - "8000:8000"
    volumes:
      - ./APIRestful/storage:/app/storage
    restart: unless-stopped
  
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - proxy_temp:/var/tmp/nginx
      - proxy_logs:/var/log/nginx
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: ./worker
    container_name: video-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./worker:/app
    depends_on:
      - redis
    command: celery -A celery_app worker --loglevel=info

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=anb
      - POSTGRES_USER=anb_user
      - POSTGRES_PASSWORD=anb_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  proxy_temp:
  proxy_logs:
  redis_data:
  postgres_data: