name: anb-cloud

services:
  api:
    build:
      context: ./APIRestful
      dockerfile: Dockerfile
    container_name: anb_api
    ports:
      - "8000:8000"
    volumes:
      - ./APIRestful/storage:/app/storage
    restart: unless-stopped
  
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - proxy_temp:/var/tmp/nginx
      - proxy_logs:/var/log/nginx
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbitpass
      - RABBITMQ_LOAD_DEFINITIONS=1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  worker:
    build: ./worker
    container_name: video-worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:rabbitpass@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
    volumes:
      - ./worker:/app
    depends_on:
      - rabbitmq
    command: celery -A celery_app worker --loglevel=info

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=anb
      - POSTGRES_USER=anb_user
      - POSTGRES_PASSWORD=anb_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  proxy_temp:
  proxy_logs:
  rabbitmq_data:
  postgres_data: