version: '3.8'

services:
  # Servicio de la API FastAPI
  api:
    build:
      context: ./APIRestful
      dockerfile: Dockerfile
    container_name: anb_api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - APP_NAME=ANB Rising Stars API
    volumes:
      # Montar carpeta storage para persistir archivos
      - ./APIRestful/storage:/app/storage
    restart: unless-stopped
