server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  # Use env var so non-OBS hosts can reach Loki over the OBS IP
  # The value is provided via .env as LOKI_URL=http://${obs_ip}:3100/loki/api/v1/push
  - url: ${LOKI_URL}

positions:
  filename: /var/log/positions.yaml

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Tell promtail which file to read for each container discovered via Docker SD
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: /var/lib/docker/containers/$1/$1-json.log

      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container

      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project

      - source_labels: ['__meta_docker_container_name']
        regex: '/(promtail|loki|grafana).*'
        action: drop

    pipeline_stages:
      - docker: {} 

